version: '3.7'
x-app_common:
  &app_common
  build:
    context: ../../
    dockerfile: ops/dev/Dockerfile
    args:
      BUNDLE_GEMS__ITG__FR: ${BUNDLE_GEMS__ITG__FR}
  env_file:
    - app_env
    - app_env.secrets
  stdin_open: true
  tty: true
  volumes:
    - app_data:/app
    - ./database.yml:/app/config/database.yml
  ports:
    - 80
  tmpfs:
    - /tmp

services:
  app:
    << : *app_common
    environment:
      VIRTUAL_HOST: hub-oxygene.syn
      VIRTUAL_PORT: 80
    networks:
      default:
          aliases:
            - hub-oxygene.syn
  memcached:
    container_name: memcached
    image: memcached:latest
    command: -m 64 -v
  sidekiq:
    <<: *app_common
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  app_data:
    driver_opts:
      type: none
      device: "${PWD}/../../"
      o: bind

networks:
  default:
    external:
      name: plungy_default
