app:
  domainName: staging-internal-itg.staging.plunge.cloud
  image: __CI_REGISTRY_IMAGE__/app:__COMMIT_TAG__
  # to run release rake
  initContainers: false
  extraEnv:
    DEPLOY_TIMESTAMP: __DEPLOY_TIMESTAMP__
    SECRET_KEY_BASE: 837b0a47a4b297f97ce3fds8a109f8e3826829f98901dac1cb1dc17f3614c3a3b8e24bffa5cc2ee4ea2b694b0b81e923fdeb8beabf5a782ff54285aff2d740d17b
    DB_DATABASE: oxygene-hub-staging-internal
    CMS_DB_DATABASE: oxygene-hub-staging-internal-services
    RAILS_ENV: production
    MAILCATCHER_ENABLED: "1"
    MAILCATCHER_HOST: mailcatcher-common-app-app
    MAILCATCHER_PORT: "1025"
    PUMA_WORKER_COUNT: "2"
    TZ: Europe/Paris
    RAILS_LOG_TO_STDOUT: 1
    MEMCACHE_SERVERS: memcached:11211
    SATISMETER_API_KEY: test
    SATISMETER_PROJECT_ID: test
    HEXAPOSTE_DIR: test
    NOVAPOST_APIKEY: test
    AWS_S3_REGION: eu-west-3
    AWS_S3_BUCKET_NAME: com.itg.itg-staging-internal
    MANAGEO_KEY: 791bb13a77154bc5996ac8ac6fa2099f
    ROLLBAR_ACCESS_TOKEN: dccb388a3d7148aeb4c38b99ed4ad1f5
    ROLLBAR_ENV: synbioz-dev1
  extraSecretEnv:
    - fromSecret:
        name: stack-postgresql-13
        data:
          DB_HOST: postgresql-host
          DB_PASSWORD: postgresql-password
          DB_USERNAME: postgresql-username
    - fromSecret:
        name: stack-redis
        data:
          REDIS_URL: redis-full-host
    - fromSecret:
        name: aws-s3-internal
        data:
          AWS_ACCESS_KEY_ID: aws_access_key_id
          AWS_SECRET_ACCESS_KEY: aws_secret_access_key
    - fromSecret:
        name: default-credentials
        data:
          ADMIN_EMAIL: email
          ADMIN_PASSWORD: password
  releaseTasks:
    - name: bootstrap
      command: ["rake"]
      weight: "-2"
      steps: "pre-install,pre-upgrade"
      args:
        - "goxygene:dev_db:create_admin_user"
cas:
  domainName: staging-internal-cas-itg.staging.plunge.cloud
  image: build.synbioz.com/itg/oxygene-cas/app:feature-ops
  # to run release rake
  initContainers: false
  extraEnv:
    DEPLOY_TIMESTAMP: __DEPLOY_TIMESTAMP__
    SECRET_KEY_BASE: 837b0a47a4b297f97ce3fds8a109f8e3826829f98901dac1cb1dc17f3614c3a3b8e24bffa5cc2ee4ea2b694b0b81e923fdeb8beabf5a782ff54285aff2d740d17b
    DB_DATABASE: oxygene-hub-staging-internal
    RAILS_ENV: production
    TZ: Europe/Paris
    RAILS_LOG_TO_STDOUT: 1
  extraSecretEnv:
    - fromSecret:
        name: stack-postgresql-13
        data:
          DB_HOST: postgresql-host
          DB_PASSWORD: postgresql-password
          DB_USERNAME: postgresql-username
    - fromSecret:
        name: stack-redis
        data:
          REDIS_URL: redis-full-host
assets:
  image: __CI_REGISTRY_IMAGE__/assets:__COMMIT_TAG__
  extraEnv:
    DEPLOY_TIMESTAMP: __DEPLOY_TIMESTAMP__
ingress:
  tls:
    secretName: wildcard-staging-plunge-cloud-crt
