apiVersion: batch/v1
kind: Job
metadata:
  name: __JOB_NAME__
  labels:
    type: delete-database
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: build.synbioz.com/synbioz/docker-images/postgresql-aws-s3/app:0.6.0-postgres-13.2
        command: [ "/bin/bash" ]
        args:
        - -c
        - |
          #!/usr/bin/env bash
          current_database=$(psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d "${POSTGRES_DB}" -c "\echo 1" | grep -c 1)
          service_current_database=$(psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d "${POSTGRES_DB}-service" -c "\echo 1" | grep -c 1)

          if [ "${current_database}" = "1" ]; then
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "ALTER DATABASE \"${POSTGRES_DB}\" CONNECTION LIMIT 0;"
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '${POSTGRES_DB}';"
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "DROP DATABASE IF EXISTS \""${POSTGRES_DB}"\";"
          fi

          if [ "${service_current_database}" = "1" ]; then
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "ALTER DATABASE \"${POSTGRES_DB}-service\" CONNECTION LIMIT 0;"
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '${POSTGRES_DB}-service';"
            psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -d postgres -c "DROP DATABASE IF EXISTS \""${POSTGRES_DB}-service"\";"
          fi
        env:
        - name: POSTGRES_DB
          value: "oxygene-hub-__ENV_NAME__"
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: stack-postgresql-13
              key: postgresql-host
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: stack-postgresql-13
              key: postgresql-username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: stack-postgresql-13
              key: postgresql-password
      imagePullSecrets:
      - name: synbioz
