bureau_consultant:
  admin:
    email: admin@itg.fr

  paginate_per_page:
    default: 10
    consultants: 50

  accounts_cache:
    duration: 12

  rss_url: 'https://www.itg.fr/portage-salarial/Les_actualites_rss?xpage=plain'
  rss_duration:
    articles: 12

  google_tag_manager_key: GTM-PWLBVML
