cfonb_path: 'uploads/cfonb120/'
riseup:
  client_id: <%= ENV['RISEUP_CLIENT_ID'] || '6e483bb2a3c615f44867aea5b86f2e17' %>
  client_secret: <%= ENV['RISEUP_CLIENT_SECRET'] || 'ebf56d4cb7d3ccc6b3969cfcc41ac0f8' %>
  site: <%= ENV['RISEUP_SITE'] || 'https://api-preprod.riseup.ai' %>
  api_root_path: <%= ENV['RISEUP_ROOT_PATH'] || '/v3' %>
  training_options_production:
    - ["Atelier Découverte du Portage Salarial", 18641]
    - ["Atelier Découverte du Portage Salarial IT", 46479]
    - ["Atelier d'intégration à la gestion de mon activité", 91408]
    - ["Journée Marketing du Conseil", 18604]
    - ["Réunion d'information", 27004]
  training_options:
    - ["Atelier Découverte du Portage Salarial", 18641]
    - ["Atelier Découverte du Portage Salarial IT", 46479]
    - ["Atelier d'intégration à la gestion de mon activité", 70860]
    - ["Journée Marketing du Conseil", 18604]
    - ["Réunion d'information", 27004]

fci:
  client_id: <%= ENV['FCI_CLIENT_ID'] || 'compte_test_itg' %>
  client_secret: <%= ENV['FCI_CLIENT_SECRET'] || '3wzZA5m5y67Jl2Fd' %>
  site: <%= ENV['FCI_SITE'] || 'https://moncompte.fci-immobilier.com' %>
  api_root_path: <%= ENV['FCI_ROOT_PATH'] || '/api_itg_to_fci' %>
client_mail_attachment_size: 10
