currency_layer:
  access_key: '520ba1ea1bc9af3c6824d85cc870fbc8'
  site: 'http://api.currencylayer.com/'
riseup:
  client_id: '6e483bb2a3c615f44867aea5b86f2e17'
  client_secret: 'ebf56d4cb7d3ccc6b3969cfcc41ac0f8'
  site: 'https://api-preprod.riseup.ai'
  api_root_path: '/v3'
  training_options:
    - ["Atelier Découverte du Portage Salarial", 18641]
    - ["Atelier Découverte du Portage Salarial IT", 46479]
    - ["Atelier d'intégration à la gestion de mon activité", 70860]
    - ["Journée Marketing du Conseil", 18604]
    - ["Réunion d'information", 27004]
